### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by joachimmetz** [arnimarj/py-leveldb#3]
First of all, thanks for putting this project out there.

Given the last commit is of 10 years ago what is the status of this project and the corresponding [PyPI package](https://pypi.org/project/leveldb)? There is also https://github.com/rjpower/py-leveldb which appears to be more recent.

If you're interested I've made some changes to address issue and add Python 3.12 support. If you're interested in a PR let me know.

**Comment by arnimarj** [comment]
> First of all, thanks for putting this project out there.
> 
> Given the last commit is of 10 years ago what is the status of this project and the corresponding [PyPI package](https://pypi.org/project/leveldb)? There is also https://github.com/rjpower/py-leveldb which appears to be more recent.
> 
> If you're interested I've made some changes to address issue and add Python 3.12 support. If you're interested in a PR let me know.

Hi. The stewardship for this project was assumed by the awesome Russell Power, and he has the publishing rights to PyPI.

If you have changes for Python 3.12, I'm sure it will be well received in the new GitHub repo.

**Comment by joachimmetz** [comment]
Thanks for the quick response. I reached out to Russell as well via https://github.com/rjpower/py-leveldb/issues/16 will wait for his response.

Closing this issue given my question was answered.
